name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.2'

    - name: Install additional packages
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libcurl4-openssl-dev

    - name: Run tests
      run: tests/run_tests.sh
